sudo: required
language: node_js
node_js:
- '8'

cache:
  directories:
  - node_modules

notifications:
  email: false

cache:
  directories:
    - $TRAVIS_BUILD_DIR/elm-stuff/build-artifacts
    - $TRAVIS_BUILD_DIR/tests/elm-stuff/build-artifacts

install:
  - npm i create-elm-app -g

script:
  - elm-app test
  - elm-app build
