sudo: false
language: node_js
node_js:
- '8'
branches:
  only:
  - master

cache:
  directories:
  - node_modules

deploy:
- provider: heroku
  api_key:
    secure: ZhyrvPUbnxAesQhA7OQQi51ydEa3vD0G4EZoW+lhQgjQW9MJAGrvH0C8fRsAXfx/QDQwx7in+g/IO506KfjHGDJuKXAvIA2zj0Bq3sWE6TynUCkbhlLmwmRiHvuuJnEbQcgZ7gOeW4t/puu3v/Tpicj7HEEyhWKHs2r/uD5LbqkEqGoxco5Q6VoS0ImJ5+g/i8GrwL2fO7uF1CHXlIbHBGvaF2/5w7wQ9QRbEHrcRZFanGiajLxL2obGYrU02HiRf0H7xsk0GJbVQtV7tNa7etFBjNZeNmul3actIY0fi59wX25glEXzy2qIld7lGIrfUGHXMSUpHw9g8LF7cWqFlm5n4e2JJlWFM46IQMM/wZVW7aQoFK65NGlVSO0zYC3rlomQU16+uiDLS+Tar+vEgTTNkbgOK/Mkzt9Ro3/vDqIs5jloH0wF65duBalFmuw9SEp0lrSE9VO4P/AAHs5cMbjZbBy785zX3UuhgdMuc3s7t1r/lD13XauVB6jNILwoCK4scPV9I2Tla6r6rnFQlYXcykZ1PjT1+pjbP4P2eurfgOaAGCYM6pK3FpBlL/2Vp6hShiUkH0wdPnygdGCG0xvX4C+1sPXuv0zyr1aQjxZ7kZdX8qilvoiILuwcindvnIqz8mHfU3gPWkQwgOKAmXELg1Co3uluc9fnK6B9+Yg=
notifications:
  email: false
